name: Lint

on:
  push:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14

      - name: Install node modules
        run: yarn

      - name: Lint project
        run: yarn lint:ci
